flags: {}
extra-package-dbs: []
packages:
- '.'
- location: /home/frank/Workspace8/uniform-strings
  extra-dep: true
- location: /home/frank/Workspace8/uniform-convenience
  extra-dep: true
- location: /home/frank/Workspace8/uniform-algebras
  extra-dep: true
- location: /home/frank/Workspace8/uniform-error
  extra-dep: true
- location: /home/frank/Workspace8/uniform-fileio
  extra-dep: true
- location: /home/frank/Workspace8/uniform-time
  extra-dep: true
- location: /home/frank/Workspace8/uniform-http
  extra-dep: true
#- location: ../rdf4store
#  extra-dep: true
extra-deps:
- data-easy-0.7.0
- rdf4h-3.0.1
resolver: lts-8.13
