flags: {}
extra-package-dbs: []
packages:
- location: /home/frank/Workspace8/uniform/uniform-strings
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-convenience
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-algebras
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-error
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-fileio
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-time
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-http
  extra-dep: true
- location: /home/frank/Workspace8/rdf4h
  extra-dep: true
- location: /home/frank/Workspace8/LitTextWork/NLPservices
  extra-dep: true
- location: /home/frank/Workspace8/TreeTagSets
  extra-dep: true
- ../LitFoundation
- ../rdf4hextension
- ../../path
- '.'
extra-deps:
- hgal-2.0.0.2
- parsec-extra-0.2.0.0
- path-0.6.1
- path-io-1.3.3
- test-invariant-0.4.5.0
resolver: lts-9.1
