flags: {}
extra-package-dbs: []
packages:
- location: /home/frank/Workspace8/uniform/uniform-strings
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-convenience
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-algebras
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-error
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-fileio
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-time
  extra-dep: true
- location: /home/frank/Workspace8/uniform/uniform-http
  extra-dep: true
- location: /home/frank/Workspace8/rdf4h
  extra-dep: true
- location: /home/frank/Workspace8/chatter
  extra-dep: true
#- location: /home/frank/Workspace8/storeInJena
#  extra-dep: true
- ../LitFoundation
- ../rdf4hextension
- '.'
extra-deps:
# - chatter-0.8.0.1
- fullstop-0.1.4
- hgal-2.0.0.2
- parsec-extra-0.2.0.0
- test-invariant-0.4.5.0
- tokenize-0.3.0
resolver: lts-9.1
