flags: {}
extra-package-dbs: []
packages:
- /home/frank/Workspace8/uniform/uniform-strings
- /home/frank/Workspace8/uniform/uniform-convenience
- /home/frank/Workspace8/uniform/uniform-algebras
- /home/frank/Workspace8/uniform/uniform-error
- /home/frank/Workspace8/uniform/uniform-fileio
- /home/frank/Workspace8/uniform/uniform-time
- /home/frank/Workspace8/uniform/uniform-http
- /home/frank/Workspace8/rdf4h
#- ../LitFoundation
- ../rdf4hextension
- .
extra-deps:
- hgal-2.0.0.2
- test-invariant-0.4.5.0
resolver: lts-10.8
